### ISSUE TITLE
New Tuya firmware from last month (SmartLife, firmware 1.6.1 on Teckin 13w bulbs)

### ISSUE THREAD

**Issue by vsaintloup** [ct-Open-Source/tuya-convert#612]
Hello, newbie here. 

I successfully used tuya-convert for all of my Tuya devices at home, although I had 4 out of 5 of some nice 13W bulbs ( https://www.amazon.com/TECKIN-Changing-Equivalent-Compatible-2900K-6000K/dp/B07RZKV7FQ/ ) were recently updated to SmartLife (tuya)'s new firmware last month version 1.6.1, so for those I had to access the PIN inside the lights in order to flash the firmware since they refused to go further than "resending packets" in the OTA process.

I am on Mac, I used the Tazmotizer app, and I did a backup of that new firmware thinking that it might help the owner of this repo to find a way to update the OTA tool in response to this new tuya patched firmware… 

If this can be of any help, just let me know where Tazmotizer stores its back-ups (I can't find this information on Google lol) and I'll send it to you! 

Thanks for your amazing work!

**Comment by vsaintloup** [comment]
Also, in case anyone is looking for the correct GPIO output for those powerful 13w RGBWW Teckin bulbs, here the correct config:

 ```
esphome:
  name: teckin_13w_rgbww
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "AirPort 2.4 GHz"
  password: "0000000000"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Light 13W Hallway"
    password: "0000000000"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "0000000000"

ota:
  password: "0000000000"

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO13
  - platform: esp8266_pwm
    id: output_cold_white
    pin: GPIO5

# Define a light entity
light:
  - platform: rgbww
    name: teckin_13w_rgbww
    id: teckin_13w_rgbww
    red: output_red
    green: output_green
    blue: output_blue
    warm_white: output_warm_white
   cold_white: output_cold_white
    cold_white_color_temperature: 6200 K
    warm_white_color_temperature: 2800 K
```
