### ISSUE TITLE
Moes ufo-r2-rf with WR3E

### ISSUE THREAD

**Issue by iMatux** [ct-Open-Source/tuya-convert#901]
Hello! Yesterday I received this IR/RF blaster from Aliexpress, I though it had an ESP chip like ufo-r1 version, but after teardown I saw that it has a WR3E chip, which seems not compatible with Tasmota, as it has a RTL chip inside, like [Tuya Developer site](https://developer.tuya.com/en/docs/iot/service-market/certification-service/general-certification/module-test-tool?id=K9qswhqd5ymnp) says.
This is a really great product has it has IR and 315/433 mhz for RF and it's really cheap.
If anyone needs pics here they are, including wiring prototype from a doc on Tuya site linked before:
![IMG_3561](https://user-images.githubusercontent.com/23347512/105016111-8b84a700-5a42-11eb-8dc6-97eee5153ad6.jpeg)
![IMG_3565](https://user-images.githubusercontent.com/23347512/105016144-93dce200-5a42-11eb-9292-0c245057ea10.jpeg)
![IMG_3568](https://user-images.githubusercontent.com/23347512/105016157-9808ff80-5a42-11eb-891d-11e1e7180e85.jpeg)
<img width="473" alt="Schermata 2021-01-19 alle 10 36 28" src="https://user-images.githubusercontent.com/23347512/105016171-9dfee080-5a42-11eb-8ce7-b891e07a108e.png">

**Comment by Python1320** [comment]
[This hint](https://esp8266.ru/forum/threads/modul-wbr3.5289/#post-75621) worked for me just today to make my [WR3E](https://developer.tuya.com/en/docs/iot/wr3e-module-datasheet?id=K9elwlqbfosbc) output ` <RTL8195A> ROM:` on a similar IR device. As I wrote [here](https://github.com/arendst/Tasmota/issues/4855#issuecomment-756707796) it seems the old esp-alike chip has been depreciated so all new devices will come with this unsupported chip from now on... so make sure to request the old version. It's probably going to take a while before anyone manages to port Tasmota or much anything to these chips.

**Comment by iMatux** [comment]
A year after I tried again, bought a Esp8266 12S, soldered without pulling any pin, flashed Tasmota and it work, now I have to figure it out how to set GPIO and template in Tasmota and it should work, hopefully.
![image](https://user-images.githubusercontent.com/23347512/149672296-b24d5b0b-8937-48a9-a625-731b6d3893e2.jpeg)

**Comment by MacSass** [comment]
Hi, 
very interesting - LED wise the interior looks very much like my YTF IR bridge (https://tasmota.github.io/docs/devices/YTF-IR-Bridge/) which still came with ESP8266 and that I´m using as IR blaster.
Due to the several LED it has a great reach - even gets "around corners", obviously reflecting at walls ...

Looking at the HW this one seems to have 3 antennas for sending - so I would guess it should have a good reach for RF too ...

I found yours on AliExpress for about 20€, which is not too bad in pricing.

I´d be interested if you find the GPIO layout (guess it should not be too hard finding it by guess and try ...

Please share your experience - thanks - MacSass

**Comment by yvesdm3000** [comment]
Hello,

Could you elaborate a bit how you open the case of this device?
Been pulling it from the side but it feels like it would damage the plastic...
Thanks !

Yves

**Comment by gonzzovela** [comment]
@yvesdm3000 I've just opened one and confirm there are no external screws.

You just need to use one of the tipical smartphone repair tools to pen it thorugh the middle. You have two tabs on each side close to the corner.

**Comment by gonzzovela** [comment]
has anyone figured out the pins used by the board? I'd like to use it by replacing the WR3E by an ESP.

Thanks,

**Comment by Agnes56fr** [comment]
How did you open it ?

**Comment by yvesdm3000** [comment]
I pried it open with a plastic tool used to open a smartphone / tablet.

 
Yves

 
-----Original message-----

**Comment by RoganDawes** [comment]
LibreTuya-ESPHome is working fine on this RTL8710-based module, fwiw. But I would love to find a way to do the initial installation OTA if possible, rather than attaching wires to the module pins.

**Comment by ChrisGroenewald** [comment]
> LibreTuya-ESPHome is working fine on this RTL8710-based module, fwiw. But I would love to find a way to do the initial installation OTA if possible, rather than attaching wires to the module pins.

@RoganDawes I'd love a bit more info on how you did it. I ended up with some RTL circuit breakers on advise from my electrician and decided I'd figure out how to integrate them later. Dumb idea.

**Comment by RoganDawes** [comment]
I'm guessing you have the CBI Astute smart controllers. The only way that I know of to flash them is to open them up, and connect wires to the appropriate pins as per the libretiny project. If you have access to a 3D printer, there are some models that can put pogo pins in the right places to save soldering, although I have not had the best results that way!

Details can be found here: http://docs.libretiny.eu/docs/platform/realtek-ambz/

Use ltchiptool once you have created a suitable config file (basically, the bare minimum, including the `ota:` and `wifi:` details.) Even with nothing wired up, ltchiptool will try to connect to it, and when it times out, will print out the wiring required. You'll also want to find the WR3E pinout to get the corresponding pins on the board/module.

**Comment by ChrisGroenewald** [comment]
You guessed correctly. I'm no stranger to the soldering iron, so it's not a problem. I'm considering picking up a spare one and playing with that first to get the process down pat. Awesome info, thank you! I'm looking forward to getting them out of the walled garden.

**Comment by RoganDawes** [comment]
Good luck. Shout if you need help with the yaml configuration.

**Comment by MayorBug** [comment]
> Good luck. Shout if you need help with the yaml configuration.

Hi Rogan, could you share your yaml configuration for this device?

**Comment by RoganDawes** [comment]
> Good luck. Shout if you need help with the yaml configuration.

This is what I had prior to the change where `libretiny` needs to be updated to the cpu platform (`rtl87xx:`). I no longer have any of these devices, so have not bothered to update it. It is strongly recommended to include the `web_server:` and `captive_portal:` components in all firmware uploaded to these devices, in case you enter the wifi credentials incorrectly!). If you are having trouble getting current and power readings from the device, try adding the `inverted:` option to the CF and CF1 pins.

```
substitutions:
  devicename: asc
  upper_devicename: Smart Controller

esphome:
  name: ${devicename}

rtl87xx:
  board: wr3e
  framework:
    version: latest

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:

wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password
  ap:
    ssid: $upper_devicename

web_server:
  port: 80

captive_portal:

sensor:
  - platform: hlw8012
    model: BL0937
    sel_pin: 
      number: PA19
      inverted: true
    cf_pin: PA15
    cf1_pin: PA14
    voltage_divider: 1742
    current:
      name: "${upper_devicename} Current"
    voltage:
      name: "${upper_devicename} Voltage"
    power:
      name: "${upper_devicename} Power"
    energy:
      name: "${upper_devicename} Energy"
    update_interval: 5s

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: PA22
      inverted: true
      mode:
        input: true
    name: "${upper_devicename} Button"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      - switch.toggle: relay_template

switch:
  - platform: output
    id: relay
    output: relay_output

  - platform: template
    name: "${upper_devicename} Relay"
    id: relay_template
    lambda: |-
      if (id(relay).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - light.turn_on: red_led
      - switch.turn_on: relay
    turn_off_action:
      - light.turn_off: red_led
      - switch.turn_off: relay
    # optimistic: true # this will change the toggle switch to individual on/off buttons

light:
  - platform: binary
    id: red_led
    output: red_led_output

output:
  - id: red_led_output
    platform: gpio
    pin: PA23
    inverted: true

  - id: relay_output
    platform: gpio
    pin: PA12
    inverted: false

# Blue LED
status_led:
    pin: 
      number: PA05
      inverted: true

```
